Default: &defaults
  database: yesodTest.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: yesodTest_test.sqlite3
  <<: *defaults

Staging:
  database: yesodTest_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: yesodTest_production.sqlite3
  poolsize: 100
  <<: *defaults
