Default: &defaults
  database: yesodMissingNo.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: yesodMissingNo_test.sqlite3
  <<: *defaults

Staging:
  database: yesodMissingNo_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: yesodMissingNo_production.sqlite3
  poolsize: 100
  <<: *defaults
